name: nginx-http-flv-module CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # Schedule for testing with the latest NGINX to run at 00:00 on the first day of every month
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        nginx-branch: [stable, mainline]
    steps:
      - uses: actions/checkout@v3

      - name: Install build and test dependencies
        run: |
          sudo apt-get --yes update
          sudo apt-get install --yes libpcre3-dev libssl-dev perl cpanminus

      - name: Create NGINX download directory
        run: mkdir nginx

      - name: Download ${{ matrix.nginx-branch }} NGINX
        uses: dvershinin/lastversion-action@v0.0.3
        with:
          repository: 'nginx'
          action: 'unzip'
          branch: ${{ matrix.nginx-branch }}
          working_directory: ./nginx

      - name: Configure NGINX to compile with the module dynamically
        run: |
          cd nginx && ./configure --with-debug --add-dynamic-module=..

      - name: Make NGINX module
        run: |
          cd nginx && make -j$(nproc) modules
